# Generated by Django 2.2.1 on 2019-08-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offcialLink', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subordinateSchoolAndCollege', models.CharField(max_length=100)),
                ('openTime', models.DateTimeField()),
                ('period', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
                ('link', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('stuCode', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('subordinateClass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('selectedCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courseRS.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectionLog', to='courseRS.User')),
            ],
        ),
    ]
