# Generated by Django 2.2.1 on 2019-08-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRS', '0003_auto_20190821_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
