# Generated by Django 2.2.1 on 2019-08-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseRS', '0004_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
    ]
