# Generated by Django 2.2.1 on 2019-08-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRS', '0005_remove_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stuCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='subordinateClass',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
