# Generated by Django 2.2.1 on 2019-08-28 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseRS', '0007_auto_20190828_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='period',
            new_name='checkInNum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='openTime',
        ),
        migrations.AddField(
            model_name='course',
            name='currentStatus',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
