# Generated by Django 2.2.1 on 2019-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRS', '0008_auto_20190828_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='LogoLink',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
