# Generated by Django 2.2.1 on 2019-08-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseRS', '0009_college_logolink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='LogoLink',
            new_name='logoLink',
        ),
    ]
